### ISSUE TITLE
Issue #1 - Gallery Page

### ISSUE THREAD

**Issue by Pisin2020** [Pisin2020/Web_DevLearning#2]
Complete the gallery page by adding images so that they come in proper grid

**Comment by AnshulGoyal589** [comment]
i would like to work on the issue, kindly assign it to me

**Comment by madm234** [comment]
![image](https://github.com/Pisin2020/Web_DevLearning/assets/88799492/a3405315-3630-4943-b69b-d21775e17836)
If I'm not wrong you want a proper section between Gallery and it's footer section which includes the same images as in the footer in a proper grid form. I can contribute to this.

**Comment by HarshwardhanPatil07** [comment]
@Pisin2020 Thanks for putting up the issue i tried fixing it
