### ISSUE TITLE
Issue #2 - About Us Page

### ISSUE THREAD

**Issue by Pisin2020** [Pisin2020/Web_DevLearning#3]
Add more sections or div in about us page so that it increases the strength

**Comment by AnshulGoyal589** [comment]
i would like to work on the issue, kindly assign it to me

**Comment by Abhishekvermaa** [comment]
Hii @Pisin2020 !!
please assign this issue to me.

**Comment by HarshwardhanPatil07** [comment]
please me @Pisin2020
