### ISSUE TITLE
Issue #4 - Elements Page

### ISSUE THREAD

**Issue by Pisin2020** [Pisin2020/Web_DevLearning#5]
Add form section in proper way in code

**Comment by AnshulGoyal589** [comment]
i would like to work on the issue, kindly assign it to me

**Comment by madm234** [comment]
I want to contribute to this issue.

**Comment by Dhananjay-12** [comment]
Hi, can i work on this ?

**Comment by HarshwardhanPatil07** [comment]
hillow! @Pisin2020
