### ISSUE TITLE
Create Documentation Readme.md file

### ISSUE THREAD

**Issue by Pisin2020** [Pisin2020/Web_DevLearning#6]
good looking or with good spacing readme file

**Comment by Lakshay938** [comment]
@Pisin2020 Please assign this issue to me.

**Comment by AnshulGoyal589** [comment]
@Pisin2020 i would like to contribute in this under hactoberfest 2023, kindly assign the issue to me

**Comment by AnshulGoyal589** [comment]
@Pisin2020 i have made the PR , please accept it under hactoberfest 2023

**Comment by avinashkrishna07** [comment]
Hii @Pisin2020 Can you please assign this to me, as i'm interested and would like to contribute on this project.
Thank you!

**Comment by HarshwardhanPatil07** [comment]
@Pisin2020 I am great and already made changes in popular repo

**Comment by Sairam-K26** [comment]
Can you assign it to me
